### ISSUE TITLE
i3 window selection stopped working

### ISSUE THREAD

**Issue by geier** [DaveDavenport/rofi#118]
I just pulled the latest release of rofi and window selection with i3 wouldn't work anymore, i.e., the dialog came up fine, but i3 would not change focus to the selected window.

This seems to have been introduced in [this commit](https://github.com/DaveDavenport/rofi/commit/072baa9c027845fad438331ee0bde5f3da03d448#diff-07a0444e8fb2e8634d25284e6a19bb3bR193). Changing `"[id=\"%ul\"] focus"` back to `"[id=\"%d\"] focus"` on today's *HEAD* does the trick for me.

**Comment by DaveDavenport** [comment]
Weird, it was giving  a compiler warning and I looked at my X definition file where it said:
```
typedef XID Window;
```

and then for XID:
```
typedef unsigned long XID;
```

So `%ul` should be correct (and seems to be working here). I took care not to break things (as far as I could tell.) and it works for me on several machines. 

What type of  system are you on? (x86 32bit/64bit, arm 32/64bit, mips? etc.?)  because this should not happen and needs to be fixed. (but %d is not correct either).

**Comment by geier** [comment]
This was on Ubuntu 14.04.1 LTS 3.13.0-43-generic #72-Ubuntu x86_64, I'll give this a go on my machine at home later tonight.

**Comment by DaveDavenport** [comment]
will check that out tomorrow, at work I should have that version somewhere running.

**Comment by DaveDavenport** [comment]
Ok. I can reproduce on PC here..
odd

**Comment by DaveDavenport** [comment]
UGH shoot me, it is obvious.  `%ul` v.s. `%lu`.. .   unsigned long is `%lu`.

I wonder if at work they switched to decaf coffee.

**Comment by geier** [comment]
:+1: and thanks for fixing this so quickly

**Comment by DaveDavenport** [comment]
no problem. Please report any bugs you can find :smile:
