### ISSUE TITLE
Possibility to pipe window selection into another command

### ISSUE THREAD

**Issue by cornerman** [DaveDavenport/rofi#196]
It would be cool if one could tell rofi to print the window id instead of changing focus when in window switcher mode. Then it would be possible to do something else with the window.

**Comment by DaveDavenport** [comment]
This is not possible and I am not sure if adding this is wise.

It is probably very easy to emulate using dmenu mode, e.g. do something like:
```bash
wmctrl -l | ./rofi -dmenu -p "window" | ./magic_script_to_do_thing.sh
````

**Comment by cornerman** [comment]
Thank you, that would work, but I will have the window ids in the rofi-selection for referencing which does not look so nice :)

The reason I am asking is because I would like to move the selected window to the current workspace instead of focusing it, which, I think, could be a common usecase. What do you think?

**Comment by DaveDavenport** [comment]
That can be solved by making a small bash script :smile:. The dmenu mode of Rofi is versatile enough for that. We can help with this if needed.  (See rofi-scripts repository and others from @carnager  for inspiration).
(the https://github.com/carnager/rofi-scripts/blob/master/monitor_layout.sh script uses a trick like this)

Implementation wise, your request does not really match with how rofi works, adding it would be a hack.
I'll leave this bug report open because maybe I come up with a creative solution to implement this cleanly (and not break combi mode and more), but don't count on it.

**Comment by cornerman** [comment]
Ah cool, I must have overlooked that option, I was able to build something according to what you said: [here](https://github.com/cornerman/dotfiles/blob/master/bin/get_window).

For this feature request: as there is a ```-run-command```, I thought it might be possible to have something similar for the window switcher. But the proposed alternative seems good enough (maybe I will even make it a mode). Thanks!

**Comment by DaveDavenport** [comment]
Nice script.. will try it out.

**Comment by carnager** [comment]
@cornerman is it ok, if we host this in https://github.com/carnager/rofi-scripts repository?

**Comment by cornerman** [comment]
@carnager Sure, feel free to add it to the repository. It is a good idea to have those scripts at one place.
