### ISSUE TITLE
Using dmenu's `-l` option only changes focus

### ISSUE THREAD

**Issue by cdown** [DaveDavenport/rofi#200]
I had a report from a user of one of my dmenu scripts about this: https://github.com/cdown/clipmenu/issues/10

I don't know much about rofi or its goals, but I guess that -dmenu is supposed to emulate dmenu as far as possible.

One difference between dmenu and rofi in dmenu mode is that `-l` in dmenu still focuses the first option, but `-l` in rofi's dmenu mode focuses the n+1th and doesn't seem to limit the number of output entries (these are both with `-l 8`):

![](http://i.imgur.com/K9D4HEK.png)

![](http://i.imgur.com/uxGGpeG.png)

I repro this on version 0.15.5.

**Comment by DaveDavenport** [comment]
Yes, the `-l` commands are not compatible.
Afraid changing this now will break several rofi apps.

**Comment by cdown** [comment]
Even ones in `-dmenu` mode? Don't any apps in `-dmenu` mode expect that whatever args get passed after are for dmenu mode only?

**Comment by DaveDavenport** [comment]
I agree this is a pitty it does not match.  (rofi option is `-lines`).
I gave up on full dmenu compatibility, because there are so many 'patches' around each with different set of (contradicting) options.

Given this is a 'base' version, maybe at next 'breaking cmds' I will fix this one.

**Comment by DaveDavenport** [comment]
@carnager would fixing this break clerk or rofi-pass?

**Comment by carnager** [comment]
It does. I am all for dmenu compatibility though. at least the options from unpatched dmenu.

**Comment by DaveDavenport** [comment]
```
       -b     dmenu appears at the bottom of the screen.
       -i     dmenu matches menu items case insensitively.
       -l lines
              dmenu lists items vertically, with the given number of lines.
       -m monitor
              dmenu appears on the given Xinerama screen.
       -p prompt
              defines the prompt to be displayed to  the  left  of  the  input
              field.
       -fn font
              defines the font or font set used.
       -nb color
              defines  the  normal background color.  #RGB, #RRGGBB, and color
              names are supported.
       -nf color
              defines the normal foreground color.
       -sb color
              defines the selected background color.
       -sf color
              defines the selected foreground color.
```

# Bottom screen
dmenu:
```
-b
```
rofi
```
-location 6
```
# Case insensitive

dmenu:
```
-i
```

rofi:
```
-no-case-sensitive
```
Option `-i` is number mode (e.g. return index to selected row)

# Monitor:
dmenu
```
-m
```
Does not exists in rofi it is placed on the monitor with focus.

# Prompt
dmenu and rofi
```
-p
```

# Lines
dmenu:
```
-l
```

rofi
```
-lines
```
In rofi `-l` means select line **n**

**Comment by DaveDavenport** [comment]
Ok. current git should be compatible now.

**Comment by cdown** [comment]
Thanks @DaveDavenport! I've got it on my todo list to check soon.

**Comment by tomseffect** [comment]
i'm not sure if it was intended but commit 8ca3c276c9d59b08d6228549b9cd718d60bc4397 breaks rofi config in regards to case sensitivity when invoking dmenu mode.

the patch starts by setting config.case_sensitive to true (at that point overriding whatever value was in config.case_sensitive), and then only sets to false if -i is specified.
the result is that running rofi in dmenu mode REQUIRES adding -i in all your scripts even if you have case-sensitive set to false in xresources.

i understand that if you want to emulate dmenu 100% this might be intended, but then perhaps you could consider adding it to the manpage.
personally, i'd rather have a global setting, but since dmenu is sensitive by default, and rofi is insensitive by default, i just changed the rofi option to case_insensitive so i can set the desired default behavior on my different machines, i can send a pull request if you'd like, but i'm not sure what the intentions were in this case...

**Comment by DaveDavenport** [comment]
your suggestion might be good.  will think about it. @carnager  opinion?
