### ISSUE TITLE
custom mode

### ISSUE THREAD

**Issue by ShionRyuu** [DaveDavenport/rofi#205]
The current [i3_switch_workspaces](https://github.com/DaveDavenport/RandomScripts/blob/master/i3_switch_workspace.sh) script doesn't  work correctly in custom mode:

```
$ rofi -modi "window,run,ssh,Workspaces:i3_switch_workspaces.sh" -show Workspaces
Failed to set lock on pidfile: Rofi already running?
-1 Resource temporarily unavailable
```

It will open a second rofi window when switch to Workspaces mode again using ctrl+tab

**Comment by carnager** [comment]
this seems to be a bug on first glance. cant get any of the custom scripts to work

**Comment by t-wissmann** [comment]
The reason is, that the version of i3_switch_workspaces you are linking to, is meant to be used differently. You can use [i3_switch_workspaces](https://github.com/carnager/rofi-scripts/blob/master/i3_switch_workspace.sh) (which is from the repo `RandomScripts` and not `rofi`!) by calling: `./i3_switch_workspaces.sh`

However, the [i3_switch_workspaces.sh](https://github.com/DaveDavenport/rofi/blob/master/Examples/i3_switch_workspaces.sh) that is shipped with rofi, works *nearly* in the way you suggested:
```
rofi -modi "window,run,ssh,Workspaces:./i3_switch_workspaces.sh" -show Workspaces
```
