### ISSUE TITLE
Is the sorting broken?

### ISSUE THREAD

**Issue by jvalencia80** [DaveDavenport/rofi#242]
I've tried the "fuzzy" and "levenshtein" options, and no one will give me the right result.

If I write "fire" I get this:

* aafire
* firefox

How is this an aceptable result? Dmenu gets it right though.

**Comment by DaveDavenport** [comment]
This is how the sorting works out.
Without sorting 'aafire' was there before 'firefox' when looking through PATH

In levenshtein aafire might be shorter distance away from fire then firefox.

A better sorting algorithm would be nice (see other bug reports about it), but it is not trivial. What works well in one case fails in another.

Suggestions welcome.

**Comment by jvalencia80** [comment]
As I understand the sorting algorithm, it is searching like Google, for example, find me every command that has **fire on it** and sort it alphabetically. The algorithm is working like I don't know what I want to run, so it finds everything available to me.

And that's the problem. I (and I suppose, many others) don't want to find based on any part of a word, but only the beginning, like **ls fire*** or **find ./ -name fire***

Why not adding a **strict mode** that enforces a regexp like this **/^\<search text\>/** on the results?

**Comment by DaveDavenport** [comment]
Regex matching easily gets very slow, but interresting to try.

Problem here is (and yes I tried), fixing it for person A will result in complaints from person B and visa verse.

**Comment by jvalencia80** [comment]
I've tried some things and this is what I got:

dmenu returns the exact same list as this command (look how even finding everything containing **fire** in it, still puts **firefox** the first result):

```bash
tigre@arch ~ $ find /usr/bin -name "*fire*"
/usr/bin/firefox
/usr/bin/aafire
/usr/bin/cacafire
/usr/bin/ffado-fireworks-downloader
```

If I sort that list alphabetically, I get results more inline with rofi's output, but it's still a bit different:

```bash
tigre@arch ~ $ find /usr/bin -name "*fire*" |sort
/usr/bin/aafire
/usr/bin/cacafire
/usr/bin/ffado-fireworks-downloader
/usr/bin/firefox
```

And if I do the strict match I get the only possible result:

```bash
tigre@arch ~ $ find /usr/bin -name "fire*"
/usr/bin/firefox
```

Even the alphabetically sorted results are better than rofi's list because you know how to search an alphabetical list, but when results are all mixed like this:

```bash
aafire
firefox
cacafire
ffado-fireworks-downloader
```


It's unintuitive to find something. If the list was bigger, it would be even worse. Look at this rofi list:

[imgur link](http://i.imgur.com/lG8NM3g.png)

It's almost impossible to find something in that list (at least for me). While I understand that sorting algorithm works for some folks, other options would be great too.

**Comment by DaveDavenport** [comment]
Currently things work like this in rofi:
It reads history and places these items on top. This is sorted by USE!

It goes through the directories in PATH and list all the files in the order the Filesystem returns them.
Sorts this list alphabetically  (case insensitive) and removes duplicates

So what you get:
<Last 25 used command sorted by use>
<Apps sorted alphabetic>

The history can be disabled!

This is the list you see without filtering.

When filtering it depends on the levenshtein option how it is displayed.
WITH levenshtein it lists it based on distance between between input and entry.
Withouth levenshtein the order is preserved.

For me (not using levenshtein) firefox is always first match, because it is most used command.

The filtering is either 'tokenized' unordered matching,  or even fuzzy matching. (here for me frf matches firefox nicely).

Adding options is not a solution, because when do you stop. If I would implement everything suggested up to now we would have 32 sorting solutions where 28 do not work to well because they are either not thought through enough and do not work, or are very specific.

If you think you can do significantly better, write a patch/propose an implementable sorting/matching algorithm and things can be discussed and others give feedback. I am open to this.


*If rofi does not work how you like it and annoys you, you are completely free to stick with dmenu. *

**Comment by carnager** [comment]
Like Dave pointed out: Disable history if you don't like it.
also you probably want to disable levensthein sorting

**Comment by jvalencia80** [comment]
I'll stick with dmenu that is fast searching what I'm looking for. Thanks for the conversation guys and sorry for the annoyances.
