### ISSUE TITLE
Sorry rofi cannot understand the key combination mod4+tab

### ISSUE THREAD

**Issue by WishCow** [DaveDavenport/rofi#290]
I'm not sure which version caused this problem, but since an update, I get the message in the title when I try to start rofi. I have this in my .Xresources:
```
rofi.key-window: mod4+Tab
```

Looking at the manpage, this syntax seems to be the correct format?

edit:
I just found out that I'm using bleeding edge from git, might be broken only in the current master. I'm on 0.15.11.r67.gff52140.

**Comment by DaveDavenport** [comment]
It is not broken, but expected behaviour.  Supporting 'mod1,mod2,mod3,mod4' directly caused problems, as I had no way to figure out reliably if the mod key is something I can use or is remapped or used as `ISO_level_`.

So try to specify it as `SuperR` (SuperL, etc.), because then rofi can actually validate if that key exists on the keyboard and can be used for this purpose.

I will update the error message to mention this.
