### ISSUE TITLE
Fullscreen, padding and opacity

### ISSUE THREAD

**Issue by p3lim** [DaveDavenport/rofi#308]
Before 93b6b83fb9fc1add7ebc781c7df20e005352acfb I could set the padding to a very high value to force extra padding and make rofi become fullscreen, but since that commit I only get a warning.

There is the `-fullscreen` argument, but that doesn't play nicely with compton and the `-opacity` argument, basically opacity seems to be ignored.

Also, `-fullscreen` seems to ignore the `-lines` argument.

**Comment by DaveDavenport** [comment]
I am not sure what the bug is.. 

but:

1. If padding is to large and no space is left for showing text rofi indeed throws a warning.
1.  Opacity being ignored is not a ROFI bug, **rofi** still set the hint _NET_WM_WINDOW_OPACITY,  compton decides to ignore this.
1. This is correct.  It tries to fit as many lines as possible.  Normally lines is determined to set height of window. When height of window is determined by monitor size, the logic reverses and the number of lines is set by the available space.

For me rofi works fine in fullscreen with rofi?  So what is the exact problem?

**Comment by DaveDavenport** [comment]
Example of compton + rofi in fullscreen: http://images.sarine.nl/rofi-fullscreen2.png

**Comment by p3lim** [comment]
Problem is (for me atleast) having rofi fullscreen with opacity.
What was the config used in that screenshot?

**Comment by DaveDavenport** [comment]
I don't have that exact config anymore, but if you set the background to be transparent, you can still get it:
Like this:
```
! Use extended color scheme
rofi.color-enabled:                  true
! Color scheme for normal row
rofi.color-normal:                   argb:0000000, #a2b5df, argb:3affffff, #a2b5df, #02143f
! Color scheme for urgent row
rofi.color-urgent:                   argb:0000000, #ff817f, argb:3affffff, #ff817f, #02143f
! Color scheme for active row
rofi.color-active:                   argb:0000000, #6aa4ff, argb:3affffff, #6aa4ff, #02143f
! Color scheme window
rofi.color-window:                   argb:ee02143f, #a2b5df, #a2b5df
! Separator style (none, dash, solid)
rofi.separator-style:                solid
```

The `argb:ee02143f`  sets the window to be around 7% transparent.

You can play with it here: https://davedavenport.github.io/rofi/generator.html

**Comment by p3lim** [comment]
I'll play around with and see if it works, thanks!

**Comment by DaveDavenport** [comment]
np. I like this way, as the text does not get transparent..

**Comment by p3lim** [comment]
You're right, this works exactly like I wanted to, thanks again!

**Comment by DaveDavenport** [comment]
Great!
