### ISSUE TITLE
What's the diff between -dmenu and -show run?

### ISSUE THREAD

**Issue by fx3O2** [DaveDavenport/rofi#339]

**Comment by DaveDavenport** [comment]
Seriously?

**Comment by DaveDavenport** [comment]
DMenu: http://tools.suckless.org/dmenu/
run:  Application launcher.

Next time please try to spend 3 seconds to look for the answer.

**Comment by fx3O2** [comment]
Still don't get the diff, look both the same. There is no need for -dmenu option. It is just an alias for -show run. Nex time please spend 3 seconds more to explain the difference. 

Thanks.

**Comment by DaveDavenport** [comment]
They are not the same. I cannot even understand why you would think it is an alias.
Doing 'rofi -show run'  or executing 'rofi -dmenu'  even act differently.
In your other bug report you are even using the `dmenu`  mode of rofi to display the output of another application.

Beside that, this is an issue tracker, not a place to dump random question where you do not even spend the effort to explain in the description.

**Comment by fx3O2** [comment]
If this is an issue tracker, please dont label issues with `question` then.

**Comment by DaveDavenport** [comment]
Because if people spend effort in actually formulating a full question (and I could see the confusion): like in #338. I don't want to be rude and try to at least answer it, I then mark it question, so a next person can search for this.

As you saw your other question, where you actually bothered to say something (yet did not formulate a question) I did not instantly close.

**Comment by carnager** [comment]
`rofi -dmenu` takes the output of another application and represents it as a list, where you can chose from.

`rofi -show run` shows all installed applications. `rofi -show drun` does the same thing, but uses the general names of applications.

Your issue is, that you used j4menu to test the -dmenu mode of rofi. passing j4menu to rofi and `-show drun` do the same thing

What you want to archive can be done with rofi alone, you don't need j4menu at all. simply run `rofi -show drun`

And most importantly: read the manpage before asking, it's all explained in there. 
And don't be rude, like you were in this and #341 case or other projects might block you too.
