### ISSUE TITLE
Priority of items in combined window and drun list

### ISSUE THREAD

**Issue by TheMuspilli** [DaveDavenport/rofi#402]
I have a second proposal concerning window switching. A separated post, because this is not connected to my other proposal.

Scenario:
Using rofi in combi mode with window and drun. I want to launch program xyz. Thus I summon rofi and use the right spell "xyz". Then I hit enter and - something "unexpected" happens. Rofi switches to the first entry in the list. I did not not pay attention to that list at all. Turns out there is an open window "firefox - foo xyz bar" (or "xyz.txt - mousepad" or ...), that had been on the pole position of rofi's list. Thus instead of launching the program I confirmed switching to the browser (editor/whatever) window that has a file open featuring "xyz". 

What I would like is an option that when ordering combined lists the order or items in the results list would be:
1. window - switch to window containing the search term in the program name (WM_CLASS?)
2. drun - launch application described by the search term
3. window - switch to window containing the search term somewhere in the window title

That way all the functionality would be still there, the priority would still be on window switching, but the first item on the list would - imho - be more likely to be the one that I actually want to choose. It is quite clear to me that also in this case the main problem sits in front of the computer, blindly confirming the wrong choices. Nevertheless I think this proposal might be agreeable not only to me.

**Comment by DaveDavenport** [comment]
I don't agree that what happens is 'unexpected' it might be 'unwanted'. 

I agree it would be nice if rofi could predict exactly what I want to do (Without using Google MindRead (tm)) but implementing a priority scheme like this would become very complex very quickly.  I don't see a way to implement something like this that is a.) clean, b.) customizable (because everybody wants it different) and c.) maintainable.

Good patches are always welcome.

**Comment by DaveDavenport** [comment]
closing for now because inactivity. Patch still welcome.
