### ISSUE TITLE
xfce4-power-manager

### ISSUE THREAD

**Issue by icf20** [DaveDavenport/rofi#473]
Version: 0.15.11
show -run

when i start rofi it show xfce4-power-manager but i dont longer have xfce4 power manager on my system, so my question is how i can remove this from the list ?

**Comment by valsoray17** [comment]
Shift-Del: Delete entry from history.
Please read the man page, it has all the info you need.

**Comment by icf20** [comment]
> Shift-Del: Delete entry from history.

is there anyway to do that automatically ?

**Comment by DaveDavenport** [comment]
Next time *please* read the guide mentioned at the top when filing an issue: [here](https://github.com/DaveDavenport/rofi/blob/master/.github/CONTRIBUTING.md).

One of the points mentioned is checking existing issues. This one has been handled and discussed many times before.
#466, #231, etc.

In short, this is caused by history, you can disable history, this wont happen. You can hit shift-delete, or in GIT once it fails running it is removed.  Doing it automatically is difficult as the list can also contain custom commands with arguments (see #466) or aliases, etc.
