### ISSUE TITLE
Use number of input lines as default for dmenu mode

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#488]
`printf '1\n2' | rofi -dmenu` uses 15 lines by default, but should only use 2.

I think the default should be to use the maximum from the number of input lines and 15, in case `-lines`/`-l` is not specified.

I think this changed recently, but have not investigated.

**Comment by DaveDavenport** [comment]
Pass -no-fixed-num-lines or  rofi.fixed-num-lines: false in configuration file.

**Comment by blueyed** [comment]
Thanks, missed that!

Doesn't it make sense as a default though?

Also from d4d757a it sounds like it should do so already?!

> Resize window to fit rows if not num-fixed-lines is set.

I see, the default was changed in d3ef6eb.

What about using the old default (false) in dmenu mode?

**Comment by DaveDavenport** [comment]
Because of Async mode that was recently introduced, I cannot center rofi correctly (as on startup the number of elements is not yet known), so I either keep re-centering (people complained about this), or center it on the entry box (people complained about this too).
No solution is right, so I enabled fixed line mode so it centers it correctly. (and more compaints :smile: )

**Comment by blueyed** [comment]
Heh.. :)

Can async mode be toggled and/or only kick in for a certain input size?
I do not see a reason to use it in simple usage patterns like above (i.e. a short list of inputs, e.g. for confirmation and selection of static menu entries).

**Comment by DaveDavenport** [comment]
There is a flag for that, but that won't change the current positioning/sizing.
Code should be kept maintainable, building in 1000123 corner cases is not that.
