### ISSUE TITLE
Incomplete README, INSTALL

### ISSUE THREAD

**Issue by AkselMeola** [DaveDavenport/rofi#510]
Your example yields this:
_$ rofi -combi-modi window,run -show combi_
> The combi switcher has not been enabled

**What does it mean ?**
**Where do I install themes, and how do I switch between them ?** 

It's an awesome app, but I should not be asked to read the source to be able use it. 

Thanks!

**Comment by DaveDavenport** [comment]
You issue is incomplete.

**What version do you use?**
**What is missing from rofi install file**
**What is the issue here**

Users are awesome, but I should not be asked to read the users mind to interact with them.

Please **read** and _**follow**_ the [guideline](https://github.com/DaveDavenport/rofi/blob/master/.github/CONTRIBUTING.md).
