### ISSUE TITLE
Using rasi themes?

### ISSUE THREAD

**Issue by bearcatsandor** [DaveDavenport/rofi#691]
Using version 1.4.1, how does one use a rasi theme? There doesn't seem to be a command line switch for that and nothing in the man pages tells me where to put the .rasi files or how to select one.

**Comment by carnager** [comment]
use `rofi-theme-selector`

**Comment by DaveDavenport** [comment]
The `-theme` flag is listed in manpage and `-h` output.

Rasi statement about `-theme` leaving traces of the default theme is incorrect.

**Comment by DaveDavenport** [comment]
The `-theme` flag is listed in manpage and `-h` output.

carnager statement about `-theme` leaving traces of the default theme is incorrect.

**Comment by bearcatsandor** [comment]
Thank you both! I have it working beautifully now.

**Comment by carnager** [comment]
Just for clarification: My statement is correct, but only if you use the new config.rasi file, which is considered alpha right now :)

**Comment by DaveDavenport** [comment]
> Just for clarification: My statement is correct, but only if you use the new config.rasi file, which is considered alpha right now :)

Wit the danger of getting in a back and forth discussion about this...

No it is not correct.  What happened was, you used the ALPHA config file to tell rofi to load theme X, then the current way to tell it to load theme Y.   Rofi nicely loaded theme X, then on top of that theme Y.
Resulting in a merge of the two themes.

So:
1. The default has never been loaded in this process.
2. This is a non-problem, because if a user follows the normal way of configuration. As it is in the manpage, this will not occur. It only happens if you start mixing the alpha (not officially released) new config format and the old way.

Why I want to have this clear is, that I think it is a very bad idea solve a non-problem for normal users, by advising to use a feature that is part of the new config format that is still in ALPHA.  This will just cause extra problems.

**Comment by DavidMetcalfe** [comment]
Perhaps the apt-get version of Rofi that I'm using is broken, but both `-h` and `man` make no useful mention of themes beyond `-dump-xresources-theme`.

**Comment by sardemff7** [comment]
Most likely an old version (0.15.12, pre-1.0 for oldest Ubuntu/Debian, and 1.3 for the newest).
If so, why the hell did you feel like adding that to an old bug report if you don’t even have a matching version? Please do not hijack bug reports (even the ones that are not really reports).
