### ISSUE TITLE
Fuzzy search still not on-par with FZF?

### ISSUE THREAD

**Issue by alexozer** [DaveDavenport/rofi#810]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Output of `rofi -v`
Version: 1.5.1-dirty (tags/1.5.1)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/8d000e38bca501289cda0a373cd1fefe

## Launch Command

The commandline used to launch **rofi**

`rofi -show drun`

## Steps to reproduce

Use this config:

```
rofi.matching: fuzzy
rofi.font: Ubuntu Mono derivative Powerline 16
rofi.modi: drun
rofi.hide-scrollbar: true
rofi.levenshtein-sort: true
```

Launch Rofi and type 'gpar' (unfortunately you'll need similar software installed as me, using with Xfce could work I think"

## What behaviour you see

I believe the first four letters of the GParted entry should be selected, but the selection seems low quality.

See: https://i.imgur.com/dgBQftn.png

## What behaviour you expect to see

fzf would definitely select the beginning of the GParted line, so I would expect that if rofi uses the fzf algorithm.

I tried fzf on the literal lines Rofi was showing and got this result, *much* better:

![fzf results](https://i.imgur.com/PbMLJA7.png)

**Comment by DaveDavenport** [comment]
Did you enable sort?

rofi.sort: true

or `rofi -sort` or hit the keybinding while running.

Also rofi matches (in drun) more fields then are visible, this might throw off the algorithm.

The algorithm was pretty similar (but utf8 compatible.) so I expect similar results on the same input data.

**Comment by alexozer** [comment]
@DaveDavenport Thanks, wasn't aware of the `sort` option and how it mixes with the other options. Enabling `sort` and disabling `levenshtein` seems to produce great results.

**Comment by BonaBeavis** [comment]
I am still having this issue with the "right" options.

Version 1.5.1
```
-[no-]disable-history                Disable history in run/ssh
False (File)
-[no-]sort                           Use sorting
True (File)
-[no-]levenshtein-sort               Use levenshtein sorting also for fuzzy matching
False (File)
fuzzy (File)
-[no-]tokenize                       Tokenize input string
```

And with `rofi -show drun` and Input `fi`, rofi returns:
```
File Manager
Application Finder
...
...
...
Firefox
```

Is there any possibility to sort in a way, that matches, beginning with the search string, appear first?

**Comment by indeedwatson** [comment]
I'm having the same problem as @BonaBeavis describes. It basically renders rofi useless as a file finder.

**Comment by DaveDavenport** [comment]
For me it seems sane:

``` rofi -show drun -sorting-method fzf -sort ``` (Git)

![rofi-2018-09-13-2036-00000](https://user-images.githubusercontent.com/406245/45508429-14191b80-b795-11e8-9538-3de6648cec23.png)
(duplicates are of testing on my side)

But if it is not working correctly, I will remove fzf.  I did not implement it myself and have no time to dive into it.

**Comment by indeedwatson** [comment]
Okay, it's not as unusable as I thought, but take a look at this:

This is `cat mpvbookmarks.txt | fzf`
https://paste.xinu.at/8Yc3A/

See how it matches letters together?

Now that same file, but through rofi
https://paste.xinu.at/SqaftA/

See where the `t` and the `m` end up?

Don't remove the fzf matching, but I think it's worth pointing out that it's not the same as fzf.

----

The rofi script that I use to get stuff from that file, just in case:

```bash
#!/bin/bash
# use with https://gist.github.com/garoto/e0eb539b210ee077c980e01fb2daef4a
file="$HOME/.config/mpv/bookmarks-playlist"
if [ -f $file  ]
then
    mpv "$(rofi -theme-str "#window {width: 90%;}" -dmenu -markup-rows -i -p \
        "video" -matching fuzzy -sort -sorting-method fzf < $file \
        | grep -Po '\/home\/yama.*|http.*|ytdl:\/\/.*')"
fi
```

**Comment by DaveDavenport** [comment]
Wonder if the highlighting actually matches the algorithm. will take a look at that.

**Comment by JihongJu** [comment]
The problem is the "fuzzy" matching. Instead of matching the characters as close as possible, rofi's fuzzy matching tries to match the character as far as possible.

For example, _ffxwb_ will match
<ins>**F**</ins>ire<ins>**f**</ins>o<ins>**x**</ins> Web Browser (<ins>**W**</ins>eb <ins>**B**</ins>rowser)
whereas I would expect:
<ins>**F**</ins>ire<ins>**f**</ins>o<ins>**x**</ins> <ins>**W**</ins>eb <ins>**B**</ins>rowser (Web Browser)

**Comment by indeedwatson** [comment]
It took so long for someone to be able to explain this. Thank you so much @JihongJu

**Comment by DaveDavenport** [comment]
> The problem is the "fuzzy" matching. Instead of matching the characters as close as possible, rofi's fuzzy matching tries to match the character as far as possible.
> 
> For example, _ffxwb_ will match
> **F**ire**f**o**x** Web Browser (**W**eb **B**rowser)
> whereas I would expect:
> **F**ire**f**o**x** **W**eb **B**rowser (Web Browser)

I am pretty sure  this is highlighting issue and not how it matches! 
@MaskRay can probably comment on this.

**Comment by fiskhest** [comment]
@DaveDavenport I could just be misunderstanding entirely, but after looking for a solution to my problem and finally seeing this reply, I'm not certain that I can agree with your assertion.

Running rofi and inputing the string `super + shift + h`
`rofi -no-config -show fb -modi fb:hkhelper.py -sorting-method fzf -sort -matching fuzzy`

produces:

![img-2020-08-18-190109](https://user-images.githubusercontent.com/26885267/90543087-6c2cd980-e185-11ea-9ed8-df17f2e4178b.png)


whilst `hkhelper.py | fzf` gives me a more sane result:

![Screenshot_2020-08-18-33_3200x1800](https://user-images.githubusercontent.com/26885267/90543110-764ed800-e185-11ea-93ce-c54f7c54cfcf.png)

**Comment by DaveDavenport** [comment]
I did not write the fzf sorter, so I cannot judge exactly what is happening, I do not use it myself.. if it is not working right and it is not going to be fixed I will remove the fzf sorting.

**Comment by MaskRay** [comment]
@fiskhest Can you provide textual form of the collection?

`-matching fuzzy` indeed uses a dynamic programming based fuzzy matching algorithm. The problem is that highlighting does not take into account how the individual characters are matched.

**Comment by DaveDavenport** [comment]
If you look here: https://github.com/davatorium/rofi/blob/next/source/view.c#L635

mode_token_match() does that matching,

then on line 647 and down it creates the 'score' for sorting. 

(state->distance[] is used to sort the results using qsort).

**Comment by fiskhest** [comment]
> @fiskhest Can you provide textual form of the collection?
> 
> `-matching fuzzy` indeed uses a dynamic programming based fuzzy matching algorithm. The problem is that highlighting does not take into account how the individual characters are matched.

You mean something like this?
```
Unhide window in stack                            super + shift + u                                 toggle show
Move or swap node to the left (desktop/leaf)      super + shift + h                                 if ! bspc node -s west.local; then bspc node -d prev -f ; fi
```

Those two lines and searching for `super + shift + h` is enough to reproduce for me, please clarify if you're asking for something else.

**Comment by DaveDavenport** [comment]
I can clearly reproduce what you describe.

**Comment by kantord** [comment]
I noticed that the fuzzy scorer works particularly bad for very long strings. I assume this is due to the scorer returning minimal score for anything longer than 256 characters.

I think some of the descriptions in rofimoji might exceed that: https://github.com/fdw/rofimoji. With rofimoji in particular I found that the matches seem to be more or less random. I think the long emoji descriptions in rofimoji show that for fuzzy matching, it might be particularly useful to have very long options with a nice searching algorithm, so that there are multiple ways you could find what you are looking for.

Would it be reasonable to increase the maximum character length, or to perhaps punish long strings less severely? For example, instead of returning minimal score for 256, only halving the score. At 512, dividing by 4, at 1024 dividing the score by 8 etc. etc.

Or perhaps somehow make the scoring mixed: give a Levenshtein score to anything that exceeds the length?

**Comment by DaveDavenport** [comment]
(not knowing fzf matching, just thinking):

Is it because it matches 's' in the first part of the string.. and uper later.

Then the 2nd entry has a lot more 'gap' between the 's' and 'super'  and that counts heavy.


so like:
![rofi-2020-08-25-2036-00000](https://user-images.githubusercontent.com/406245/91214178-03a8a400-e713-11ea-9eff-e583d2fcffe7.png)

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/blob/master/src/fuzzy_match.cc has a simple fuzzy searching implementation and it works pretty well in practice.

I thought about contributing it but rofi grabs mouse/keyboard so it is really difficult to debug.

```
cgdb --args Debug/rofi -dmenu -sort -matching fuzzy -input /tmp/p/ctags/tags
r
# My mouse/keyboard is locked. I have to switch to a virtual console to kill gdb.
```

**Comment by MaskRay** [comment]
OK, I just realized that `-matching fuzzy` (I used for a long time) no longer enables the fuzzy matching algorithm. `-sorting-method fzf` needs to be used instead. IMHO this really causes confusion. Moreover, `fzf` is a misnomer because the algorithm has nothing to do with `fzf`. fzf is not invoked as an external process.

Created #1173 to fix the issue and created #1174 to improve `-sorting-method fuzzy` performance a bit.

**Comment by DaveDavenport** [comment]
I think it was originally called fzf as it implemented scoring as implemented in fzf (at that point in time).

**Comment by OJFord** [comment]
It's not just a highlighting issue, `fzf` prioritises longer matching strings, so that `abcd` sorts for `abcd` ahead of `abc...d`.

On the input `echo -e 'abcccccd\nabcd\nabcccd' | /usr/bin/dmenu` (dmenu symlinked to rofi), rofi doesn't change the order at all when searching `'abcd'`, output is the same three input lines in the same order.

`fzf` given the same query reorders to show `abcd`, `abcccd`, `abcccccd`.

Aside from whether you want to improve this or not, I agree that it would be better named 'fuzzy' than 'fzf', which although generic on the face of it ('fuzzy find') is widely understood to refer to a specific tool, which isn't being used here.

**Comment by DaveDavenport** [comment]
This works for me:
```echo -e 'abcccccd\nabcd\nabcccd' | rofi -dmenu -matching fuzzy -sort-method fzf -sort```

![rofi-2020-10-14-0916-00000](https://user-images.githubusercontent.com/406245/95956040-09129880-0dfe-11eb-9a13-17143da9b088.png)

**Comment by OJFord** [comment]
Ah, I was missing `-sort`... :facepalm: 

If the default is `sort: false, sorting-method: normal`, perhaps `sorting-method: none` instead could avoid this, so that `sort` isn't needed and setting it to anything implies sorting? Perhaps I'm missing a use case for having a sorting method defined without it being enabled.

**Comment by DaveDavenport** [comment]
Sort enable/disable can be triggered at run-time using a keybinding. its why it is separated.

**Comment by OJFord** [comment]
Ah, ok. :+1: Apologies for noise.

**Comment by DaveDavenport** [comment]
no problem.

**Comment by MaskRay** [comment]
> Ah, I was missing `-sort`... 
> 
> If the default is `sort: false, sorting-method: normal`, perhaps `sorting-method: none` instead could avoid this, so that `sort` isn't needed and setting it to anything implies sorting? Perhaps I'm missing a use case for having a sorting method defined without it being enabled.

I think this is an issue about an inconvenient default. Currently 3 options are needed to enable fuzzy finding: `-matching fuzzy -sort-method fzf -sort`

**Comment by DaveDavenport** [comment]
It is what it is,  I had -sort/-sort-method merged before and this caused more confusion.

**Comment by MaskRay** [comment]
Maybe have a master option of fuzzy sorting related features? The current way things are organized, fuzzy finding has poor discoverability and people just keep coming to comment on this issue.
