### ISSUE TITLE
Using non-monospaced fonts

### ISSUE THREAD

**Issue by memeplex** [DaveDavenport/rofi#839]
I'm skipping the requested formalities because, lacking a forum, this is more of a simple question and I assume the answer is "no, and it will never do". But just in case my assumption is wrong: does rofi support non-monospaced fonts? Obviously it accepts and renders them, but the menus are completely ill-aligned in that case. If that's a bug or there is a desire to support that feature, I'll open a more formal request. Thanks.

**Comment by DaveDavenport** [comment]
I had a forum, that was hardly used.  There is now /r/rofi on reddit for more general discussions.
This issue tracker is the wrong place.

The misalignment is obvious,  Doing the alignment right with non-monospace fonts is gonna be terribly expensive (because the width of every entry in every column needs to be calculated first (by rendering the string)) and will slow downs rofi.
