### ISSUE TITLE
Calculator Script for rofi

### ISSUE THREAD

**Issue by michix** [DaveDavenport/rofi#921]
I am missing a simple calculator script which I created and I will add with a Pull Request.

**Comment by DaveDavenport** [comment]
I don't mind adding a link to this script on the wiki. I prefer not to ship these scripts with rofi itself. 

The reason is, that it puts the burden of maintaining and updating the script with the rofi developers.
In previous programs I wrote I had very bad experience with that, and caused me so much extra work (I had no intterest in doing) it resulting in me having to abandon the project. I want to avoid this with rofi.

(The scripts that are currently there are really as examples for implementation and are also not installed  and therefore not usable by users.)

**Comment by michix** [comment]
OK, I'm fine with that.  I can understand your point. Thanks for your work on Rofi!!!

**Comment by DaveDavenport** [comment]
Feel free to add it to the wiki.
